package foxiwhitee.hellmod.localization;

import foxiwhitee.hellmod.utils.localization.LocalizationUtils;

public enum CustomGuiText {
    inventory("container"),
    Chest,
    StoredEnergy,
    Of,
    Condenser,
    Drive,
    GrindStone,
    SkyChest,
    VibrationChamber,
    SpatialIOPort,
    LevelEmitter,
    Terminal,
    Interface,
    Config,
    StoredItems,
    StoredStacks,
    Patterns,
    ImportBus,
    ExportBus,
    CellWorkbench,
    NetworkDetails,
    StorageCells,
    IOBuses,
    IOPort,
    BytesUsed,
    Types,
    QuantumLinkChamber,
    PortableCell,
    NetworkTool,
    PowerUsageRate,
    PowerInputRate,
    Installed,
    EnergyDrain,
    StorageBus,
    Priority,
    Security,
    Encoded,
    Blank,
    Unlinked,
    Linked,
    SecurityCardEditor,
    NoPermissions,
    WirelessTerminal,
    Wireless,
    CraftingTerminal,
    FormationPlane,
    Inscriber,
    QuartzCuttingKnife,
    METunnel,
    ItemTunnel,
    RedstoneTunnel,
    EUTunnel,
    FluidTunnel,
    OCTunnel,
    LightTunnel,
    RFTunnel,
    PressureTunnel,
    GTTunnel,
    IFACETunnel,
    StoredSize,
    CopyMode,
    CopyModeDesc,
    PatternTerminal,
    CraftingPattern,
    ProcessingPattern,
    Crafts,
    Creates,
    And,
    With,
    Substitute,
    BeSubstitute,
    Yes,
    No,
    MolecularAssembler,
    StoredPower,
    MaxPower,
    RequiredPower,
    Efficiency,
    InWorldCrafting,
    inWorldFluix,
    inWorldPurificationCertus,
    inWorldPurificationNether,
    inWorldPurificationFluix,
    inWorldSingularity,
    ChargedQuartz,
    NoSecondOutput,
    OfSecondOutput,
    MultipleOutputs,
    Stores,
    Next,
    SelectAmount,
    Lumen,
    Empty,
    ConfirmCrafting,
    Stored,
    Crafting,
    Scheduled,
    CraftingStatus,
    RemainingOperations,
    Cancel,
    ETA,
    ETAFormat,
    SwitchCraftingSimulationDisplayMode,
    FromStorage,
    ToCraft,
    CraftingPlan,
    CalculatingWait,
    Start,
    Bytes,
    Set,
    CraftingCPU,
    Automatic,
    CoProcessors,
    Simulation,
    Missing,
    CraftingStepLimitExceeded,
    NoCraftingTreeReceived,
    RequestedItem,
    SimulationIncomplete,
    InterfaceTerminal,
    NoCraftingCPUs,
    Clean,
    InvalidPattern,
    UnknownItem,
    InterfaceTerminalHint,
    Range,
    TransparentFacades,
    TransparentFacadesHint,
    NoCraftingJobs,
    CPUs,
    FacadeCrafting,
    inWorldCraftingPresses,
    ChargedQuartzFind,
    Included,
    Excluded,
    Partitioned,
    PartitionedOre,
    Precise,
    Fuzzy,
    Filter,
    SmallFontCraft,
    LargeFontCraft,
    PatternTerminalEx,
    Renamer,
    OreFilterLabel,
    HoldShiftForTooltip,
    HoldShiftClick_HIGHLIGHT_INTERFACE,
    Nothing,
    VoidCellTooltip,
    Deprecated,
    TypeMachine,
    TypeManaPool;

    private final String root;

    CustomGuiText() {
        this.root = "gui.appliedenergistics2";
    }

    CustomGuiText(String r) {
        this.root = r;
    }

    public String getLocal() {
        return LocalizationUtils.localize(getUnlocalized());
    }

    public String getUnlocalized() {
        return this.root + '.' + this;
    }
}
